services:
  web:
    env_file: "dev.env"
    build: .
    ports:
      - "${EXPOSE_PORT}:${CONTAINER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: ["app"]
  db:
    env_file: "dev.env"
    image: "postgres"
    restart: always
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: